version: "3.7"

services:
  mongodb_container:
    container_name: mongodb-auth
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    platform: linux/amd64
    volumes:
      - ./data-replica:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 3
      MONGO_AUTHENTICATION_DATABASE: admin
      AUTHENTICATION_MODE: PRIMARY
    ports:
      - 27018:27017 d