version: "3.7"

services:
  mongodb_container:
    container_name: mongodb
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 3
    ports:
      - 8011:27017
